# Generated by Django 5.0.6 on 2024-05-19 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_pword', models.CharField(max_length=50)),
                ('shift_start', models.TimeField(default='')),
                ('shift_end', models.TimeField(default='')),
            ],
            options={
                'db_table': 'user_tb',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('work_date', models.DateField(default='')),
                ('start_time', models.TimeField(default='')),
                ('end_time', models.TimeField(default='')),
                ('longtime1', models.FloatField(default='')),
                ('longtime2', models.FloatField(default='')),
                ('latetime1', models.FloatField(default='')),
                ('latetime2', models.FloatField(default='')),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.user')),
            ],
            options={
                'db_table': 'work_tb',
            },
        ),
    ]
