# Generated by Django 5.0.6 on 2024-05-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('work_date', models.DateField(default='')),
                ('exit_time', models.TimeField(default='')),
                ('longtime2', models.FloatField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.user')),
            ],
            options={
                'db_table': 'exit_tb',
            },
        ),
    ]
