# Generated by Django 5.0.6 on 2024-05-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0003_alter_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='shorttime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exit',
            name='status',
            field=models.CharField(default='absend', max_length=20),
        ),
        migrations.AlterField(
            model_name='exit',
            name='exit_time',
            field=models.TimeField(default='00:00:00.00000'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='longtime2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_time',
            field=models.TimeField(default='00:00:00.00000'),
        ),
        migrations.AlterField(
            model_name='work',
            name='latetime1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='latetime2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='longtime1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='longtime2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_time',
            field=models.TimeField(default='00:00:00.00000'),
        ),
    ]
