# Generated by Django 5.0.6 on 2024-05-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0004_exit_shorttime_exit_status_alter_exit_exit_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exit',
            old_name='longtime2',
            new_name='extratime',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='shorttime',
        ),
        migrations.RemoveField(
            model_name='work',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='work',
            name='latetime2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='longtime1',
        ),
        migrations.RemoveField(
            model_name='work',
            name='longtime2',
        ),
    ]
